global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:5000"]
    metrics_path: /metrics
  - job_name: "ml_service"
    static_configs:
      - targets: ["ml_service:8000"]
    metrics_path: /metrics
  - job_name: "iot_engine"
    static_configs:
      - targets: ["iot_engine:9000"]
    metrics_path: /metrics
